### ISSUE TITLE
install-plug-in-chrome.md instructions don't seem to work on windows

### ISSUE THREAD

**Issue by nickbax** [Psychedelic/plug#123]
Hi, not a big deal but the instructions for installing need a minor change to work on Windows 10. 

Simply dragging the .zip file over the extensions folder didn't work for me. 

Instead, user needs to enable developer mode, unzip the file, and then select 'Load unpacked' and select the folder containing the unzipped directory. 

Tested on Windows 10 on both Chrome and Brave

Chrome:
Chrome 91.0.4472.164 (Official Build) (64-bit)
Brave: 
Version 1.27.108 Chromium: 92.0.4515.107 (Official Build) (64-bit)

**Comment by kanej** [comment]
Thanks for that @nickbax, we will update the instructions.
