### ISSUE TITLE
Does this wallet support nft? Doesn't support other tokens?

### ISSUE THREAD

**Issue by rapid520** [Psychedelic/plug#136]
Does this wallet support nft? Doesn't support other tokens?

**Comment by kanej** [comment]
Hey @rapid520, thanks for getting in touch; both `nft` support and alternate tokens are on our roadmap. We intend to roll out custom token support in the coming weeks.

**Comment by rapid520** [comment]
> and alternate tokens are on our roadmap. We intend to roll out custom token support in the coming weeks.

How do you distinguish between nft and tokens?

**Comment by kanej** [comment]
We are still in the planning stages, for custom tokens we looking at the token standards the community has generated:

* Toniq Labs Extendable Token - https://github.com/Toniq-Labs/extendable-token
* Psychdelic's own Token Standard - https://github.com/Psychedelic/standards/tree/main/standards/token-interface

Do you have particular ideas/requirements you think important to supporting nfts?

**Comment by rapid520** [comment]
> We are still in the planning stages, for custom tokens we looking at the token standards the community has generated:
> 
> * Toniq Labs Extendable Token - https://github.com/Toniq-Labs/extendable-token
> * Psychdelic's own Token Standard - https://github.com/Psychedelic/standards/tree/main/standards/token-interface
> 
> Do you have particular ideas/requirements you think important to supporting nfts?

It is best for nft to be independent, separate from the token, and have a separate tab.

**Comment by kanej** [comment]
@rapid520 thanks for the feedback, we will keep your ideas in mind when working through our designs and plans for `NFT` support.
