### ISSUE TITLE
Icpunks

### ISSUE THREAD

**Issue by barklexfundz** [Psychedelic/plug#198]
please i can fid my nfts in my plug wallet anymore why is that happening because its just totally strange to me i urge this team to please help ressolve this glitch so i can be rest assured about this platform.

Thanks.

**Comment by rocky-fleek** [comment]
Hi @barklexfundz ! Are you still experiencing the issue? 
Punks not showing up is usually related with the IC Punks canister (contract) being down and the info not available. 
If the problem persists, could I request OS, browser and plug version?
