### ISSUE TITLE
How to get the ICP Account ID

### ISSUE THREAD

**Issue by rapid520** [Psychedelic/plug#230]
Are there any functions or methods here? Is there an example?

**Comment by kanej** [comment]
Hello,

To get the account id for plug, log into plug, and then click on deposit:

![image](https://user-images.githubusercontent.com/24030/135421706-a06a9116-400e-492f-a12f-db75225698f6.png)

Select ICP then click continue, you should be taken to the Deposit page

![image](https://user-images.githubusercontent.com/24030/135421954-6bdc4942-7488-4f33-9702-a77ff541133b.png)

The account id is displayed as the second option. You should be able to copy the id from there.

**Comment by rapid520** [comment]
> Hello,
> 
> To get the account id for plug, log into plug, and then click on deposit:
> 
> ![image](https://user-images.githubusercontent.com/24030/135421706-a06a9116-400e-492f-a12f-db75225698f6.png)
> 
> Select ICP then click continue, you should be taken to the Deposit page
> 
> ![image](https://user-images.githubusercontent.com/24030/135421954-6bdc4942-7488-4f33-9702-a77ff541133b.png)
> 
> The account id is displayed as the second option. You should be able to copy the id from there.

I mean how to get ICP Account ID through javascript
