### ISSUE TITLE
dfx identity import failed from exported pem

### ISSUE THREAD

**Issue by yvvw** [Psychedelic/plug#263]
v0.3.x v0.4 same issue

![image](https://user-images.githubusercontent.com/15168529/138201471-2ab15658-83b4-4e74-9429-25d121b6e29e.png)
![image](https://user-images.githubusercontent.com/15168529/138201577-2b9a0ad1-2b40-4712-ba07-7566d2543162.png)

**Comment by afmsavage** [comment]
Same issue
Mac
Plug 0.4.1
DFX 0.8.3

Comparing to an identity that the `dfx` cli created, they're pretty different.  Looks like `dfx` is using `PKCS11` to create its pem files.  Not exactly sure what Plug is using.

**Comment by tomiir** [comment]
Hey! Sorry about the delay. 
There seems to be a bug in dfx 0.8.1+ regarding SECP256K1 identities. If you set the dfx version to 0.8 in your `dfx.json` file, and import, it should work just fine. You can then change back the version in the dfx.json. 
Hope this helps!

**Comment by riveign** [comment]
@afmsavage any comments on @tomiir message?

**Comment by rapid520** [comment]
the same one

**Comment by riveign** [comment]
@rapid520 As of release 0.5.2 you can import you pem exported (with this new version) in any version of DFX. Closing the ticket
