### ISSUE TITLE
I cannot see ICP wallet in new plugin version

### ISSUE THREAD

**Issue by AminKarami** [Psychedelic/plug#264]
Hi. I have an issue with ICP wallet. I only can see my ICP wallet using "plug-chrome-0.2.0" plugin. If I use a newer version (such as v0.4.0), it shows my wallet empty!!! What is the problem? Please advice.

**Comment by tomiir** [comment]
Hi! Sorry about the delay. This kinds of issues are usually sorted in our discord, next time, drop us a message there! 
I hope this has been sorted out but in case it hasnt, we have a good troubleshooting guide for these issues:
https://docs.plugwallet.ooo/resources/troubleshooting-tokens/

Try those out and if it doesnt work please leave a message in our discord! 🙏

**Comment by riveign** [comment]
Closing this issue given is not a code issue.
