### ISSUE TITLE
NFT index off by 1

### ISSUE THREAD

**Issue by timohanke** [Psychedelic/plug#332]
When an NFT is part of a series and the individual NFT's index is displayed then it seems to be off by 1 when compared to the index displayed on entrepot. Seems like one is 0-based and the other 1-based.

**Comment by rocky-fleek** [comment]
Hi! The difference is a terminology one. 
We use the **index** of the NFTs in the collection, which start at 0, while Entrepot uses a **minting number** which starts at 1. 
I'll close this issue, but if you want to discuss this further you can always drop a message on the discord public channel!
