### ISSUE TITLE
After my project is connected to the plug wallet, when the browser is refreshed, my IC contract obtains the msg  The caller is incorrect

### ISSUE THREAD

**Issue by ai-blib** [Psychedelic/plug#339]
![image](https://user-images.githubusercontent.com/76576519/149653474-b5d2e5c9-8704-425a-a86b-7a975b3d37a1.png)
After my project is connected to the plug wallet, when the browser is refreshed, Execute the above method,my IC contract obtains the msg.caller is incorrect

**Comment by rocky-fleek** [comment]
Hi! Could you please provide the dfinity agent library version you are using to create your actors?
plug uses `@dfinity/agent` version 0.9.3. If you are using V10+ then principal serialization will break as they are not compatible.

Also, I'd suggest you use the `createActor` method to create your actors instead of using the agent, to prevent getting warning messages on your update calls to asset canisters.

**Comment by ai-blib** [comment]
> Hi! Could you please provide the dfinity agent library version you are using to create your actors? plug uses `@dfinity/agent` version 0.9.3. If you are using V10+ then principal serialization will break as they are not compatible.
> 
> Also, I'd suggest you use the `createActor` method to create your actors instead of using the agent, to prevent getting warning messages on your update calls to asset canisters.

the problem is not here。  The first time to enter the page，will call window.ic.plug.requestConnect ，All my method calls are normal。will create an identity，but refresh the page，Will go through the following process to get isconnect。const connected = await window.ic.plug.isConnected() ,will return true,description is link status。but , the user identity has been lost。I call my method and find that the identities are anonymous。
There is no problem with the way I call it, because it is completely normal when I do not refresh the page

![image](https://user-images.githubusercontent.com/76576519/153544434-0c79463a-0f0b-4154-80ba-f9c233f89710.png)

**Comment by ainightf** [comment]
I also encountered the same problem. How did you solve it?

**Comment by ai-blib** [comment]
You can try to see if the agent pollutes the plug. For example, the place where other agents are used can be deleted, and the test line
<img width="451" alt="image" src="https://user-images.githubusercontent.com/76576519/175853699-9dc1ab93-a794-4f3e-a662-36b30dfe3396.png">
