### ISSUE TITLE
Plug wallet has no pop-up window after approve call

### ISSUE THREAD

**Issue by CodeAunt** [Psychedelic/plug#369]
Hi, my using plug wallet's pop-up confirm window didn't turn up, and the operation is executed directly without confirmation. And these calls related to asset transfer(approve WICP token) or update didn't trigger the pop-up window either. All the pop-up windows I have ever seen are normal connect confirmation window with no warning on it.
The actor is created by:
```
window.ic.plug.createActor()
```
And the plug has connected to the site.
using plug wallet version 0.4.6, chrome 96.0.4664.45 on mac arm64

**Comment by riveign** [comment]
@CodeAunt Hey thanks for the report we are looking into this!

**Comment by riveign** [comment]
We bielve this issue has been fixed, let us know if it persist in you case
