### ISSUE TITLE
Test on local network, throw error "Fail to verify certificate"

### ISSUE THREAD

**Issue by himyyy** [Psychedelic/plug#379]
The motoko server had recevied a call, and debug the caller's principal, but throw the error.
This is my code : 
<img width="830" alt="image" src="https://user-images.githubusercontent.com/13343279/154814509-d51a7efb-868a-4c5e-9a12-e27c959134de.png">

And the error message:
<img width="598" alt="image" src="https://user-images.githubusercontent.com/13343279/154814639-f44d17d9-ab2f-44f6-b9cb-537f7225fb99.png">

**Comment by tomiir** [comment]
Hey! You can fix that by calling `await ic.plug.agent.fetchRootKey()`

This will be automatically called on non-mainnet urls on plug's next release though!

**Comment by himyyy** [comment]
Ok, This is what i do. Thanks.

**Comment by brxwjh** [comment]
still occur the problem, even when i called `await ic.plug.agent.fetchRootKey()` before `ic.plug.createActor` on local net, my plug version is `alpha-0.6.4.1`.
