### ISSUE TITLE
Confused about the connect state returned by `window.ic.plug.isConnected` method

### ISSUE THREAD

**Issue by himyyy** [Psychedelic/plug#381]
Plug version: 0.4.7
Chrome version: 98.0.4758.102 

Repro steps:
1.Go to [sonic](https://app.sonic.ooo/swap), do not connect the plug, copy the following code to console
```
const getPlugConnected = async () =>  {
  const isConnected = await window.ic.plug.isConnected();
  console.log("isConnected", isConnected);
};

getPlugConnected();
```
Print `false`

2.Connected the plug wallet, then run `getPlugConnected()` in console. Print `true`

3.Go to "My Account" page, lock the plug wallet, then run `getPlugConnected()`. Print `true`

I thought what step 3 print should be `false`, because the plug is locked by now

**Comment by tomiir** [comment]
Hi! 
Even though the wallet is locked, you are indeed connected to the page. 
If the page then tries to interact with plug in any way, the pop up will show the login screen first for the user to log in.
