### ISSUE TITLE
why there is no api document?How to call IC Management canister methods?

### ISSUE THREAD

**Issue by curry1211** [Psychedelic/plug#386]
Why there is no api documentation?
CreateActor only canisterId and interfaceFactory params, How to call IC Management canister methods?

**Comment by tomiir** [comment]
Hi! You can find documentation on the Inpage Provider API here:
https://docs.plugwallet.ooo/getting-started/connect-to-plug/

Specifically, for the createActor method, it's located here: https://docs.plugwallet.ooo/getting-started/connect-to-plug/#createactor-making-safe-calls

Let us know if you have any other doubts!

**Comment by riveign** [comment]
Closing the issue.
