### ISSUE TITLE
Make ledger canister configurable

### ISSUE THREAD

**Issue by danielterwiel** [Psychedelic/plug#392]
I'd like to configure the ledger canister ID to support testing my plug integration on a local machine with a mock ledger. Right now it is hard-coded: https://github.com/Psychedelic/plug-controller/blob/0c26dcde7a144d05cf42c3fa8682027bd038b3e8/src/utils/dfx/constants.ts

Could it be possible to place this feature request on the backlog sometime? Would be highly appreciated!

**Comment by riveign** [comment]
This will be part of release 0.5.3

**Comment by danielterwiel** [comment]
> This will be part of release 0.5.3

That's good news! Thanks for picking this up

**Comment by riveign** [comment]
@danielterwiel closing the issue since this feature has been released!
