### ISSUE TITLE
[Bug] Animation issue on hovering accounts icon.

### ISSUE THREAD

**Issue by ChristopherTrimboli** [Psychedelic/plug#429]
![Screenshot 2022-04-22 153629](https://user-images.githubusercontent.com/27584221/164817860-ebc2248a-846b-40e2-b830-d8ce184fcb74.png)

On Windows 11 Chromium.

On the edge of the hover interaction, the icon jumps around and looks bad.

**Comment by Sona9146** [comment]
Hello Can I work on it?

**Comment by ChristopherTrimboli** [comment]
> Hello Can I work on it?

I was planning to work on this on Monday, but if you want to give it a go... absolutely, feel free!
Submit a PR and we will review it :)

**Comment by ChristopherTrimboli** [comment]
fixed in PR: https://github.com/Psychedelic/plug/pull/438
