### ISSUE TITLE
WICP was not sent from PlugWallet to Stoic

### ISSUE THREAD

**Issue by kom1n** [Psychedelic/plug#482]
Hello,
I sent a WICP from Plug to Stoic but it didn't arrive (https://dashboard.internetcomputer.org/account/33d8485170a0b7fb16314db89e44c53edbdd402d4d25f665d90228611140a364). 

I don't see it on either the starting wallet or the destination one. I don't even see it among the transactions on https://dashboard.internetcomputer.org/account/b1aea4232927d66fe69800627f006722a891335328c064fa89e3c4276be8469d

It only shows up in the list of transactions in the Plug wallet Chrome plugin. Can you help me?

**Comment by riveign** [comment]
Hi @kom1n if you see the WICP transaction in plug wallet then the transaction was fulfilled, if its not appearing on stoic wallet try contacting the stoic team to check or make sure that they are showing the same implementation of WICP token (there are different standards atm). In plug we are using Dip20.
