### ISSUE TITLE
Import Identity Front End

### ISSUE THREAD

**Issue by riveign** [Psychedelic/plug#531]
# Description

We want to support importing a pem identity through the extension 

[https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=8117%3A1877](https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=8117%3A1877)

**Comment by Cancuuu** [comment]
- check what happens if user drops another file if one file already in the state
- check what happens if user drops more than one file
- maybe we could show different error messages for those cases 👆🏻👆🏻

**Comment by karlamiesesfleek** [comment]
--delete this comment--
