### ISSUE TITLE
window.ic.plug.requestTransfer failed 

### ISSUE THREAD

**Issue by neptune0xf** [Psychedelic/plug#573]
**When use window.ic?.plug?.requestTransfer({xxx}) got this error**  I am sure params is absolutely valid

![image](https://user-images.githubusercontent.com/103205025/186451035-e351ee85-4234-40c7-a826-94c22b4d5756.png)
And plug extension got this 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/103205025/186451772-24fc5913-a650-4e24-9d5d-ac11a738a565.png">

**Comment by riveign** [comment]
@neptune0xf hey! this was fixed in version 0.5.4! Please let us know if this persist :D I will close the issue
